//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace I18nConfigRessources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class traduction {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal traduction() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("I18nConfigRessources.Properties.traduction", typeof(traduction).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string btn_ajouter {
            get {
                return ResourceManager.GetString("btn_ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string btn_annuler {
            get {
                return ResourceManager.GetString("btn_annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string btn_modifier {
            get {
                return ResourceManager.GetString("btn_modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer sélection.
        /// </summary>
        public static string btn_supprimer_selection {
            get {
                return ResourceManager.GetString("btn_supprimer_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer tout.
        /// </summary>
        public static string btn_supprimer_tout {
            get {
                return ResourceManager.GetString("btn_supprimer_tout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Décompte.
        /// </summary>
        public static string lbl_decompte {
            get {
                return ResourceManager.GetString("lbl_decompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string lbl_nom {
            get {
                return ResourceManager.GetString("lbl_nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        public static string lbl_prenom {
            get {
                return ResourceManager.GetString("lbl_prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone.
        /// </summary>
        public static string lbl_tel {
            get {
                return ResourceManager.GetString("lbl_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string menu_accueil {
            get {
                return ResourceManager.GetString("menu_accueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string menu_anglais {
            get {
                return ResourceManager.GetString("menu_anglais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donateurs.
        /// </summary>
        public static string menu_donations {
            get {
                return ResourceManager.GetString("menu_donations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string menu_francais {
            get {
                return ResourceManager.GetString("menu_francais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        public static string menu_langue {
            get {
                return ResourceManager.GetString("menu_langue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnes.
        /// </summary>
        public static string menu_personnes {
            get {
                return ResourceManager.GetString("menu_personnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un redémarrage est nécessaire pour appliquer les changements. Voulez-vous redémarrer?.
        /// </summary>
        public static string msg_confirmation_redemarrage {
            get {
                return ResourceManager.GetString("msg_confirmation_redemarrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom est nom valide.
        /// </summary>
        public static string msg_erreur_nom {
            get {
                return ResourceManager.GetString("msg_erreur_nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le prénom est non valide.
        /// </summary>
        public static string msg_erreur_prenom {
            get {
                return ResourceManager.GetString("msg_erreur_prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le téléphone est non valide.
        /// </summary>
        public static string msg_erreur_tel {
            get {
                return ResourceManager.GetString("msg_erreur_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string titre_erreur {
            get {
                return ResourceManager.GetString("titre_erreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string titre_question {
            get {
                return ResourceManager.GetString("titre_question", resourceCulture);
            }
        }
    }
}
